# Convolution neural network

## Import packages

In [18]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Softmax, Conv2D, MaxPooling2D
print(tf.__version__)

2.5.0


## Build a Sequential model

### Build a feedforward neural network model

In [14]:
model = Sequential([
    Flatten(input_shape=(28,28), name='flatten_input'),
    Dense(16, activation='relu', name='layer_1'),
    Dense(16, activation='relu'),
    Dense(10, activation='softmax')
])

In [8]:
model.weights

[<tf.Variable 'dense_3/kernel:0' shape=(784, 16) dtype=float32, numpy=
 array([[-0.05345589, -0.02543506, -0.02952024, ..., -0.03133025,
         -0.08269908, -0.07967298],
        [ 0.05504334,  0.01158687,  0.08550917, ...,  0.05450128,
          0.0037153 ,  0.04203881],
        [-0.07555945, -0.01934282,  0.00882289, ...,  0.07493354,
         -0.03480026, -0.06102623],
        ...,
        [ 0.01150401, -0.01339255, -0.03498307, ..., -0.01368033,
         -0.08300551,  0.04469581],
        [-0.03383607,  0.08529156, -0.05601843, ...,  0.08387242,
          0.05372016,  0.0813103 ],
        [ 0.03009177,  0.01206789,  0.03534387, ..., -0.06646185,
          0.0011178 ,  0.07109925]], dtype=float32)>,
 <tf.Variable 'dense_3/bias:0' shape=(16,) dtype=float32, numpy=
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       dtype=float32)>,
 <tf.Variable 'dense_4/kernel:0' shape=(16, 16) dtype=float32, numpy=
 array([[ 0.274107  , -0.05465114, -0.3827435 , -0.298

In [15]:
model.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten_input (Flatten)      (None, 784)               0         
_________________________________________________________________
layer_1 (Dense)              (None, 16)                12560     
_________________________________________________________________
dense_10 (Dense)             (None, 16)                272       
_________________________________________________________________
dense_11 (Dense)             (None, 10)                170       
Total params: 13,002
Trainable params: 13,002
Non-trainable params: 0
_________________________________________________________________


## Build a Convolutional and pooling model

In [30]:
model = Sequential([
    Conv2D(16, (3,3), padding='same', strides=2, activation='relu', input_shape=(28, 28, 1)),
    MaxPooling2D((3,3), strides=3),
    Flatten(),
    Dense(10, activation='softmax')
])

In [31]:
model.summary()

Model: "sequential_11"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_6 (Conv2D)            (None, 14, 14, 16)        160       
_________________________________________________________________
max_pooling2d_5 (MaxPooling2 (None, 4, 4, 16)          0         
_________________________________________________________________
flatten_7 (Flatten)          (None, 256)               0         
_________________________________________________________________
dense_16 (Dense)             (None, 10)                2570      
Total params: 2,730
Trainable params: 2,730
Non-trainable params: 0
_________________________________________________________________
