#### 1. Import the numpy package as in the name `np` (easy)

In [34]:
import numpy as np

#### 2. Please print out the numpy version and the configuration (easy)

In [ ]:
print(np.__version__)

1.19.5


#### 3. How can we find the memory size of any array (easy)

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print("Size of the array: %d" % arr.size)
print("Memory Size of one array element in bytes: %d" % arr.itemsize)
print("Memory Size of array in bytes: %d" % (arr.itemsize * arr.size))

Size of the array: 5
Memory Size of one array element in bytes: 8
Memory Size of array in bytes: 40


#### 4. Let create a null vector of size 10 (easy)

In [ ]:
vec = np.empty(shape=(10,))

#### 5. Show how to get the documentation of the numpy add function from the command line? (easy)

In [ ]:
help(np.add)

#### 6. Let create a null vector of size 10 but the fifth value which is 1 (easy)

In [ ]:
vec = np.empty(shape=(10,))
vec[4]= 1
vec

array([4.68266505e-310, 4.68266356e-310, 0.00000000e+000, 0.00000000e+000,
       1.00000000e+000, 8.27578358e-313, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000])

#### 7. Create a vector with values ranging from 10 to 49 (easy)

In [ ]:
vec = np.array(range(10, 50))
vec

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (i.e., first element becomes last) (easy)

In [ ]:
vec = np.flip(vec)
vec

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Could you define a 3x3 matrix with values ranging from 0 to 8 (easy)

In [ ]:
matrix = np.array(range(0, 9)).reshape((3,3))
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from `[1,2,0,0,4,0]` (easy)

In [ ]:
vec = np.array([1,2,0,0,4,0])
np.where(vec != 0)

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (easy)

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (easy)

In [ ]:
np.random.rand(3,3,3)

array([[[0.17436953, 0.55227798, 0.96987736],
        [0.15760617, 0.06657278, 0.60188776],
        [0.34964365, 0.03560665, 0.10065778]],

       [[0.37046697, 0.1057132 , 0.13569082],
        [0.71344739, 0.85344846, 0.37795848],
        [0.18533109, 0.17828959, 0.58328328]],

       [[0.51969337, 0.98237328, 0.05715939],
        [0.92328154, 0.86101962, 0.12166584],
        [0.12132203, 0.38311479, 0.13427153]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (easy)

In [ ]:
arr = np.random.rand(10, 10)
print(arr)
print('max:', arr.max())
print('min:', arr.min())

[[0.2338629  0.26374189 0.11331945 0.6563878  0.29754379 0.22202041
  0.28442664 0.03166334 0.44360938 0.09022485]
 [0.03498677 0.09727775 0.42644763 0.99996456 0.56054476 0.4820527
  0.9534083  0.95055844 0.481741   0.41806792]
 [0.25706993 0.20745496 0.00811172 0.76799212 0.12936005 0.64718125
  0.18150999 0.72615794 0.39504322 0.337575  ]
 [0.12816537 0.76677939 0.79552226 0.96646325 0.1590741  0.33687594
  0.95561534 0.61743986 0.40756615 0.10453775]
 [0.45984523 0.04914905 0.66769519 0.33966206 0.31415942 0.16096431
  0.35815947 0.76263667 0.8914944  0.01942198]
 [0.64302015 0.9541432  0.05132702 0.70451439 0.66556773 0.29397917
  0.60022008 0.96921124 0.75559503 0.97935729]
 [0.84298902 0.00839826 0.19056889 0.76258378 0.25932167 0.68748553
  0.08545562 0.8641557  0.85158351 0.49885834]
 [0.98040805 0.58103374 0.61008812 0.05695018 0.59926811 0.41464785
  0.43522587 0.46176637 0.06046347 0.71815764]
 [0.44873269 0.01938196 0.20992943 0.89214714 0.59749402 0.32402429
  0.66110877 

#### 14. Create a random vector of size 30 and find the mean value (easy)

In [ ]:
vec = np.random.rand(30)
vec.mean()

0.5086673133228482

#### 15. Make a 2d array with 1 on the border and 0 inside (easy)

In [ ]:
arr = np.ones((5,5))
arr[1:-1,1:-1] = 0
arr

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (easy)

In [ ]:
arr = np.ones((5,5))
arr = np.pad(arr, pad_width=1, mode='constant', constant_values=0)
arr

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (easy)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
0 * np.nan

nan

In [ ]:
np.nan == np.nan

False

In [ ]:
np.inf > np.nan

False

In [ ]:
np.nan - np.nan

nan

In [ ]:
np.nan in set([np.nan])

True

In [ ]:
0.3 == 3 * 0.1

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (easy)

In [ ]:
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (easy)

In [ ]:
arr = np.zeros((8,8))
for row in range(8):
  arr[row][row%2:7+row%2:2] = 1
arr

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

#### 20. Consider a (6,7,8) shape array, what is the index `(x,y,z)` of the 100th element? (easy)

In [ ]:
np.unravel_index([100], (6, 7, 8))

(array([1]), array([5]), array([4]))

#### 21. Create a checkerboard 8x8 matrix using the tile function (easy)

In [ ]:
a = [[1,0], [0,1]]
a = np.tile(a, 4)
a = np.tile(a, (4, 1))
print(a)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


#### 22. Normalize a 5x5 random matrix (easy)

In [ ]:
a = np.random.rand(5, 5)
s = a.sum()
a = a / s
print(a)

[[0.05837914 0.01278258 0.05171167 0.04692944 0.03503044]
 [0.06414632 0.06854816 0.06875911 0.02787983 0.00879414]
 [0.05256276 0.05533635 0.00015475 0.01505131 0.06563948]
 [0.05654732 0.01993364 0.0490871  0.00070801 0.06614007]
 [0.04234733 0.00751894 0.03241775 0.0581114  0.03548298]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (easy)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (easy)

In [ ]:
a = np.random.rand(5, 3)
b = np.random.rand(3, 2)
c = np.dot(a, b)
print(c.shape)

(5, 2)


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (easy)

In [ ]:
a = np.array(range(10))
a[3:9] *= -1
a

array([ 0,  1,  2, -3, -4, -5, -6, -7, -8,  9])

#### 26. What is the output of the following script? (easy)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (easy)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
z = 3
print(z**z)
print(2 << z >> 2)
print(z < -z)
print(1j*z)
print(z/1/1)
print(z<z>z)

27
4
False
3j
3.0
False


#### 28. What are the result of the following expressions? (easy)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [35]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


#### 29. How to round away from zero a float array ? (easy)

In [41]:
a = np.array([1.1, 2.2, 3.3])
a = a.round()
a

array([1., 2., 3.])

#### 30. How to find common values between two arrays? (easy)

In [36]:
a = np.array([1,2,3,4,5,6,7])
b = np.array([4,5,6,7,8,9])
c = np.intersect1d(a, b)
c

array([4, 5, 6, 7])

#### 31. How to ignore all numpy warnings (not recommended)? (easy)

In [37]:
np.warnings.filterwarnings('ignore')

#### 32. Is the following expressions true? (easy)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [38]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

In [40]:
print(np.sqrt(-1))
print(np.emath.sqrt(-1))

nan
1j


#### 33. How to get the dates of yesterday, today and tomorrow? (easy)

In [42]:
from datetime import date, timedelta
today = date.today()
yesterday = today - timedelta(days=1)
tomorrow = today + timedelta(days=1)
print(yesterday)
print(today)
print(tomorrow)

2021-08-22
2021-08-23
2021-08-24


#### 34. How to get all the dates corresponding to the month of July 2016? (intermediate)

#### 35. How to compute `((A+B)*(-A/2))` in place (without copy)? (intermediate)

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (intermediate)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (intermediate)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (easy)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (intermediate)

#### 40. Create a random vector of size 10 and sort it (intermediate)

#### 41. How to sum a small array faster than np.sum? (intermediate)

#### 42. Consider two random array A and B, check if they are equal (intermediate)

#### 43. Make an array immutable (read-only) (intermediate)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (intermediate)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (intermediate)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (intermediate)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix `C` `(Cij =1/(xi - yj))` (intermediate)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (intermediate)

#### 49. How to print all the values of an array? (intermediate)

#### 50. How to find the closest value (to a given scalar) in a vector? (intermediate)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (intermediate)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (intermediate)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? (intermediate)

#### 54. How to read the following file? (intermediate)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (intermediate)

#### 56. Generate a generic 2D Gaussian-like array (intermediate)

#### 57. How to randomly place p elements in a 2D array? (intermediate)

#### 58. Subtract the mean of each row of a matrix (intermediate)

#### 59. How to sort an array by the nth column? (intermediate)

#### 60. How to tell if a given 2D array has null columns? (intermediate)

#### 61. Find the nearest value from a given value in an array (intermediate)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (intermediate)

#### 63. Create an array class that has a name attribute (intermediate)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (advanced)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (advanced)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (intermediate)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (advanced)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (advanced)

#### 69. How to get the diagonal of a dot product? (advanced)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (advanced)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (advanced)

#### 72. How to swap two rows of an array? (advanced)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (advanced)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (advanced)

#### 75. How to compute averages using a sliding window over an array? (advanced)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (advanced)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (advanced)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (advanced)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (advanced)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (advanced)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (advanced)

#### 82. Compute a matrix rank (advanced)

#### 83. How to find the most frequent value in an array? (advanced)

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (advanced)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (advanced)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (advanced)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (advanced)

#### 88. How to implement the Game of Life using numpy arrays? (advanced)

#### 89. How to get the n largest values of an array (advanced)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (advanced)

#### 91. How to create a record array from a regular array? (advanced)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (advanced)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (advanced)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (advanced)

#### 95. Convert a vector of ints into a matrix binary representation (advanced)

#### 96. Given a two dimensional array, how to extract unique rows? (advanced)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (advanced)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (advanced)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (advanced)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (advanced)