# kNN and Naive Bayes

## 1. Import important packages

In [24]:
import numpy as np
import pandas as pd

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

from sklearn.neighbors import KNeighborsClassifier

from sklearn.datasets import fetch_20newsgroups
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import make_pipeline
from imblearn.under_sampling import RandomUnderSampler
from imblearn.pipeline import make_pipeline as make_pipeline_imb
from imblearn.metrics import classification_report_imbalanced

from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import average_precision_score
from sklearn.metrics import precision_recall_curve
from sklearn.metrics import plot_precision_recall_curve

## 2. Load raw data

In [25]:
# train data
train_data = pd.read_csv('input/train_data.csv', sep=',')

In [26]:
train_data.sample(frac=1)
# train_data['classification']

text classification
18  Yêu cầu thu hồi tiền thuê đất tại dự án ngàn t...        thời sự
57  Nữ sinh giành học bổng 7 tỷ đồng từ đại học hà...       giáo dục
26                Cao su Phước Hòa chia cổ tức kỷ lục        thời sự
5               Hai anh em tử vong dưới hố công trình        thời sự
15  Xoài chín đầy cây vẫn không hái vì có hái cũng...        thời sự
33             PGA Championship cắt loại như thế nào?       thể thao
27                Griezmann lập siêu phẩm ở vòng cuối       thể thao
31                    Real bất lực dù thắng vòng cuối       thể thao
28  Lewandowski lập kỷ lục ghi bàn trong một mùa B...       thể thao
39  HLV Nishino tiếc khi học trò bỏ rơi tuyển Thái...       thể thao
25       5 lời khuyên về đầu tư cho người mới bắt đầu        thời sự
14  Phát hiện nhiều container hàng quá cảnh vi phạ...        thời sự
19   Tiền số - Cuộc chơi không dành cho người yếu tim        thời sự
41        Real 2 - 1 Villarreal hiệp 2 Modric ghi bàn       thể thao
49         Lập kế hoạch ôn thi Vật lý để đạt điểm cao       giáo dục
3    Điều kiện nào cho phép F1 có thể cách ly tại nhà        thời sự
42  Bí quyết đạt điểm 9-10 môn Sinh trong kỳ thi t...       giáo dục
0     Danh sách ứng cử viên đại biểu quốc hội khoá XV        thời sự
11  Bình Dương có thu nhập bình quân đầu người cao...        thời sự
23  Agribank miễn 100% phí dịch vụ chuyển tiền tro...        thời sự
36  Klopp: 'Man City khó vô địch nếu mất nhiều quâ...       thể thao
30                  Real lần đầu trắng tay sau 11 năm       thể thao
40              Messi Tôi thích thức dậy cùng các con       thể thao
2     Hà Nội cách ly tòa Park 9 khu đô thị Times City        thời sự
9      Bệnh gout nặng có thể thuyên giảm nhờ cách sau        thời sự
45          Phương pháp hệ thống lý thuyết hóa hữu cơ       giáo dục
47          Chiến lược giải đề Vật lý tốt nghiệp THPT       giáo dục
56            Ba thách thức khi du học Mỹ từ bậc THPT       giáo dục
53  Tuyển 200 học sinh lớp 6 vào trường chuyên Hà ...       giáo dục
13  Chỉ tiêu tăng trưởng năm 2021 là 6% GDP bình q...        thời sự
52  Lưu ý khi ôn tập hình học giải tích trong khôn...       giáo dục
48  Top 5 nhóm ngành có nhiều thí sinh đăng ký ngu...       giáo dục
24  S&P nâng triển vọng kinh tế Việt Nam lên tích cực        thời sự
55  Học bổng đến 40.000 USD từ các trường THPT nội...       giáo dục
29                Suarez: 'Barca không coi trọng tôi'       thể thao
50     Hơn 790.000 thí sinh đăng ký xét tuyển đại học       giáo dục
32                    Atletico Madrid vô địch La Liga       thể thao
38  Nữ võ sĩ taekwondo Trương Thị Kim Tuyền giành ...       thể thao
44     Đừng học thuộc lòng nếu muốn điểm cao môn Sinh       giáo dục
1                    Số ca nhiễm trong nước vượt 2000        thời sự
37  Kane: 'Mourinho thất bại vì Tottenham thiếu th...       thể thao
34  HLV Nishino tiếc khi học trò bỏ rơi tuyển Thái...       thể thao
22                     Giá vàng tăng liên tiếp 3 tuần        thời sự
6                  Hà Nội lập chốt kiểm soát Covid-19        thời sự
8      Ngày đầu quán ăn nhỏ ở Sài Gòn chỉ bán mang đi        thời sự
54         Nữ sinh mê game giành học bổng 6.8 tỷ đồng       giáo dục
21    Elon Musk cân nhắc xây dựng nhà máy Tesla ở Nga        thời sự
51        Thêm trường THPT chuyên hoãn thi vào lớp 10       giáo dục
10                      Bầu cử sớm trong vùng cách ly        thời sự
46  Sinh viên nhận song bằng tại trường Cao đẳng H...       giáo dục
16     Masan xây dựng hệ sinh thái tiêu dùng - bán lẻ        thời sự
43  Học phí các trường quốc tế ở Hà Nội năm học 20...       giáo dục
20  Chủ tịch SSI Chứng khoán năm nay tốt hơn năm n...        thời sự
35           Mbappe có thể đã đạt thỏa thuận với Real       thể thao
12                    Cần tăng thu nhập cho người dân        thời sự
7   Hải Dương lấy mẫu xét nghiệm cho hơn 39.000 người        thời sự
4                Tiêu hủy gần 1.000 con lợn nhập khẩu        thời sự
17  Cảnh báo mạo danh tin nhắn của Vietcombank 

In [27]:
# test data
test_data = pd.read_csv('input/test_data.csv', sep=',')

In [28]:
# test_data['classification']
test_data.sample(frac=1)

text classification
10            Klopp: 'Liverpool đang ở đỉnh phong độ'       thể thao
5   Tháo gỡ 'nút thắt' hơn 2.800 tỷ đồng vốn bảo t...        thời sự
6   Cao tốc TP HCM - Mộc Bài tăng vốn gần 2.300 tỷ...        thời sự
1       Hiện trạng khu vực quy hoạch đô thị sông Hồng        thời sự
7                   Trạm BOT Đông Hưng thu phí từ 1/6        thời sự
0           40 km quy hoạch phân khu đô thị sông Hồng        thời sự
2   Thủ tướng: Tập trung xây cao tốc cho những vùn...        thời sự
3               5 dự án cao tốc Bắc Nam sắp khởi công        thời sự
21  Học phí các trường quốc tế ở Hà Nội năm học 20...       giáo dục
17  Tuyển futsal Việt Nam làm quen sân thi đấu trư...       thể thao
11  BĐTV trực tiếp trận tranh vé dự World Cup futs...       thể thao
13  Liverpool vào top 4 tranh vé dự Champions Leag...       thể thao
22  Nam sinh TP HCM nhận học bổng 100% CATS Academ...       giáo dục
15                       Chờ Liverpool tung nước rút       thể thao
4   Gần 3.800 tỷ đồng xây đường kết nối Thái Nguyê...        thời sự
18  Thủ môn vô tình sút bóng vào lưới nhà y như bá...       thể thao
28  Giành học bổng 6.2 tỷ đồng bằng bài luận nhảy múa       giáo dục
24       Cách chinh phục hai đại học top đầu thế giới       giáo dục
8   Khách đi xe ôm xe buýt ở TP HCM phải khai báo ...        thời sự
27  Săn học bổng Mỹ đến 7 tỷ đồng tại St. Thomas M...       giáo dục
25  10 trường kinh doanh có tỷ lệ chấp nhận thấp n...       giáo dục
9      Làm cao tốc từ Đồng Tháp đi TP HCM còn 2 tiếng        thời sự
19  Hoàng Đức hồi phục thần tốc tuyển Việt Nam làm...       thể thao
20           Đại học Y dược TP HCM không tăng học phí       giáo dục
23  3 lộ trình du học chuyển tiếp ngành thiết kế m...       giáo dục
29                 Kinh nghiệm săn học bổng Fulbright       giáo dục
14  Ngược dòng trước Man Utd tại Old Trafford Live...       thể thao
26                     5 lỗi bài luận xin học bổng Mỹ       giáo dục
12                Lời thỉnh nguyện của Harry Kane       thể thao
16                     Juventus PSG đoạt cúp quốc gia       thể thao

In [29]:
X_train = train_data["text"]
y_train = train_data["classification"]
X_test = test_data["text"]
y_test = test_data["classification"]
y_test_actual = y_test.to_numpy()

In [30]:
y_test_actual

array(['thời sự', 'thời sự', 'thời sự', 'thời sự', 'thời sự', 'thời sự',
       'thời sự', 'thời sự', 'thời sự', 'thời sự', 'thể thao', 'thể thao',
       'thể thao', 'thể thao', 'thể thao', 'thể thao', 'thể thao',
       'thể thao', 'thể thao', 'thể thao', 'giáo dục', 'giáo dục',
       'giáo dục', 'giáo dục', 'giáo dục', 'giáo dục', 'giáo dục',
       'giáo dục', 'giáo dục', 'giáo dục'], dtype=object)

## 3. Apply Multinomial Naive Bayes without balancing data

In [31]:
imbalanced_pipeline = make_pipeline(TfidfVectorizer(), MultinomialNB())
imbalanced_pipeline.fit(X_train, y_train)
y_imbalanced_pred = imbalanced_pipeline.predict(X_test)

In [32]:
for i in range(len(X_test)):
  print(f"{X_test[i]} : {y_imbalanced_pred[i]}")

40 km quy hoạch phân khu đô thị sông Hồng : thời sự
Hiện trạng khu vực quy hoạch đô thị sông Hồng : thời sự
Thủ tướng: Tập trung xây cao tốc cho những vùng động lực : thời sự
5 dự án cao tốc Bắc Nam sắp khởi công : thời sự
Gần 3.800 tỷ đồng xây đường kết nối Thái Nguyên Bắc Giang Vĩnh Phúc : thời sự
Tháo gỡ 'nút thắt' hơn 2.800 tỷ đồng vốn bảo trì đường sắt : giáo dục
Cao tốc TP HCM - Mộc Bài tăng vốn gần 2.300 tỷ đồng : thời sự
Trạm BOT Đông Hưng thu phí từ 1/6 : thời sự
Khách đi xe ôm xe buýt ở TP HCM phải khai báo y tế : thời sự
Làm cao tốc từ Đồng Tháp đi TP HCM còn 2 tiếng : thời sự
Klopp: 'Liverpool đang ở đỉnh phong độ' : thời sự
BĐTV trực tiếp trận tranh vé dự World Cup futsal 2021 Việt Nam - Lebanon : thời sự
Lời thỉnh nguyện của Harry Kane : thời sự
Liverpool vào top 4 tranh vé dự Champions League tận giờ chót : thời sự
Ngược dòng trước Man Utd tại Old Trafford Liverpool tiến sát top 4 : thời sự
Chờ Liverpool tung nước rút : thời sự
Juventus PSG đoạt cúp quốc gia : thời 

In [34]:
# accuracy
print('accuracy = ',accuracy_score(y_test_actual, y_imbalanced_pred))

accuracy =  0.5333333333333333


In [35]:
# confusion matrix
cnf_matrix = confusion_matrix(y_test_actual, y_imbalanced_pred)
cnf_matrix

array([[ 7,  0,  3],
       [ 0,  0, 10],
       [ 1,  0,  9]])

## 4. Apply Multinomial Naive Bayes with balancing data

In [36]:
balanced_pipeline = make_pipeline_imb(TfidfVectorizer(), RandomUnderSampler(), MultinomialNB())
balanced_pipeline.fit(X_train, y_train)
y_balanced_pred = balanced_pipeline.predict(X_test)

In [37]:
for i in range(len(X_test)):
  print(f"{X_test[i]} : {y_balanced_pred[i]}")

40 km quy hoạch phân khu đô thị sông Hồng : thời sự
Hiện trạng khu vực quy hoạch đô thị sông Hồng : thời sự
Thủ tướng: Tập trung xây cao tốc cho những vùng động lực : thời sự
5 dự án cao tốc Bắc Nam sắp khởi công : thời sự
Gần 3.800 tỷ đồng xây đường kết nối Thái Nguyên Bắc Giang Vĩnh Phúc : giáo dục
Tháo gỡ 'nút thắt' hơn 2.800 tỷ đồng vốn bảo trì đường sắt : giáo dục
Cao tốc TP HCM - Mộc Bài tăng vốn gần 2.300 tỷ đồng : giáo dục
Trạm BOT Đông Hưng thu phí từ 1/6 : giáo dục
Khách đi xe ôm xe buýt ở TP HCM phải khai báo y tế : thời sự
Làm cao tốc từ Đồng Tháp đi TP HCM còn 2 tiếng : giáo dục
Klopp: 'Liverpool đang ở đỉnh phong độ' : thể thao
BĐTV trực tiếp trận tranh vé dự World Cup futsal 2021 Việt Nam - Lebanon : thời sự
Lời thỉnh nguyện của Harry Kane : giáo dục
Liverpool vào top 4 tranh vé dự Champions League tận giờ chót : thể thao
Ngược dòng trước Man Utd tại Old Trafford Liverpool tiến sát top 4 : thể thao
Chờ Liverpool tung nước rút : thời sự
Juventus PSG đoạt cúp quốc gia

In [40]:
# accuracy
print('accuracy = ',accuracy_score(y_test_actual, y_balanced_pred))

accuracy =  0.6333333333333333


In [41]:
# confusion matrix
cnf_matrix = confusion_matrix(y_test_actual, y_balanced_pred)
cnf_matrix

array([[10,  0,  0],
       [ 2,  4,  4],
       [ 5,  0,  5]])

## 5. Apply kNN

In [42]:
# vectorize X train data
vectorizer = TfidfVectorizer()
X_train_knn = vectorizer.fit_transform(X_train).toarray()
vocab = vectorizer.get_feature_names()

In [43]:
# encode y train data
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(y_train)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)

onehot_encoder = OneHotEncoder(sparse=False)
y_train_knn = onehot_encoder.fit_transform(integer_encoded)

In [44]:
y_train_knn

array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [45]:
# vectorize X test data
X_test_knn = vectorizer.transform(X_test).toarray()

In [46]:
# apply kNN
kNN = KNeighborsClassifier(n_neighbors=5)
kNN.fit(X_train_knn, y_train_knn)

KNeighborsClassifier()

In [47]:
# predict
y_pred = kNN.predict(X_test_knn)

In [48]:
y_pred

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [49]:
# print classification
classification_pred = []
for pred in y_pred:
  inverted = label_encoder.inverse_transform([np.argmax(pred)])
  label = str(inverted[0])
  classification_pred.append(label)

for i in range(len(y_test)):
  print(f"'{y_test[i]}' : {classification_pred[i]}")

'thời sự' : giáo dục
'thời sự' : giáo dục
'thời sự' : giáo dục
'thời sự' : thời sự
'thời sự' : thời sự
'thời sự' : giáo dục
'thời sự' : thời sự
'thời sự' : giáo dục
'thời sự' : thời sự
'thời sự' : giáo dục
'thể thao' : thể thao
'thể thao' : thời sự
'thể thao' : giáo dục
'thể thao' : giáo dục
'thể thao' : giáo dục
'thể thao' : thời sự
'thể thao' : giáo dục
'thể thao' : giáo dục
'thể thao' : thể thao
'thể thao' : thời sự
'giáo dục' : giáo dục
'giáo dục' : giáo dục
'giáo dục' : giáo dục
'giáo dục' : giáo dục
'giáo dục' : giáo dục
'giáo dục' : giáo dục
'giáo dục' : giáo dục
'giáo dục' : giáo dục
'giáo dục' : giáo dục
'giáo dục' : giáo dục


In [50]:
# accuracy
print('accuracy = ',accuracy_score(y_test_actual, classification_pred))

accuracy =  0.5333333333333333


In [51]:
# confusion matrix
cnf_matrix = confusion_matrix(y_test_actual, classification_pred)
cnf_matrix

array([[10,  0,  0],
       [ 5,  2,  3],
       [ 6,  0,  4]])